### ISSUE TITLE
Artefacts on Sonatype

### ISSUE THREAD

**Issue by pbugnion** [ASIDataScience/dynamic-configuration#3]
At the moment, the artefacts are pushed to ASI's private S3 repository. We should push the artefacts to Sonatype.

**Comment by srstevenson** [comment]
If we want an immediate short term solution, we can host a Maven repository on [Bintray](https://bintray.com/docs/usermanual/formats/formats_mavenrepositories.html).

**Comment by srstevenson** [comment]
The group ID `com.asidatascience` is registered now, and PR #16 adds the necessary configuration to release to Sonatype.

**Comment by pbugnion** [comment]
Thanks for doing that.

**Comment by srstevenson** [comment]
Resolved by #16.
