### ISSUE TITLE
Artefacts on Maven Central

### ISSUE THREAD

**Issue by pbugnion** [ASIDataScience/dynamic-configuration#5]
It would be good to eventually have the artefacts available in Maven Central. This is less important than #3 , but would still be useful.

As a prerequisite, we need to register the group ID `com.asidatascience`.

**Comment by srstevenson** [comment]
I've opened [OSSRH-32741](https://issues.sonatype.org/browse/OSSRH-32741) to register the group ID `com.asidatascience`.

**Comment by srstevenson** [comment]
Resolved by #16.
